modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "modutilities"
version = "${version}"
displayName = "Modutilities"
authors = "Alex Krieg"
description = '''
Utilities for modding
'''
#logoFile = ""

[[dependencies.modutilities]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modutilities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modutilities]]
modId = "architectury"
mandatory = true
versionRange = "[10.1.20,)"
ordering = "AFTER"
side = "BOTH"
